//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_out
    {
        public int id { get; set; }
        public string mechanic { get; set; }
        public string partName { get; set; }
        public string partType { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
