//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class toolsInventoryEntities1 : DbContext
    {
        public toolsInventoryEntities1()
            : base("name=toolsInventoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<check_out> check_out { get; set; }
        public virtual DbSet<mechanic> mechanics { get; set; }
        public virtual DbSet<mechanic_tools> mechanic_tools { get; set; }
    }
}
